name: flypbook
description: App to practice English

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  http: ^0.13.3
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.8
  circles_background: ^0.0.2
  flutter_animate: ^4.1.1+1
 
  permission_handler: ^10.2.0
  animations: ^2.0.7
  google_mobile_ads: ^3.0.0
  animated_background: ^2.0.0
  flutter_tts: ^3.0.0
  flutter_translate: ^4.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/onboarding/first.png
    - lib/assets/onboarding/second.png
    - lib/assets/onboarding/three.png
    - lib/assets/onboarding/four.png
    - lib/assets/onboarding/five.png
    - lib/assets/onboarding/first.jpg
    - lib/assets/restaurants/fast_food.jpg
    - lib/assets/restaurants/casual_restaurant.jpg
    - lib/assets/restaurants/cafe_restaurant.jpg
    - lib/assets/stores/supermarket.jpg
    - lib/assets/stores/hypermarket.jpg
    - lib/assets/stores/departament_store.jpg
    - lib/assets/public_transports/bus.png
    - lib/assets/public_transports/subway.gif
    - lib/assets/morning_routines/morning_routine.jpg
    - lib/assets/morning_routines/morning_routine_students.jpg
    - lib/assets/cooking_recipes/cooking_breakfast.jpg
    - lib/assets/cooking_recipes/cooking_meal.jpeg
    - lib/assets/cooking_recipes/cooking_dinner.jpg
    - lib/assets/fitness_exercises/gym.jpg
    - lib/assets/fitness_exercises/home_exercise.jpg
    - lib/assets/fitness_exercises/yoga.jpg
    - lib/assets/hobbies_interests/movie_series.jpg
    - lib/assets/hobbies_interests/music_instruments.jpg
    - lib/assets/hobbies_interests/gardening.jpg
    - lib/assets/family_time/board_games.jpg
    - lib/assets/family_time/family_cooking.jpg
    - lib/assets/technology_gadgets/virtual_reality.jpg
    - lib/assets/technology_gadgets/smart_home.jpg
    - lib/assets/technology_gadgets/wearable_tech.jpg
    - lib/assets/weekend_plans/outdoor_adventures.jpg
    - lib/assets/weekend_plans/artistic_pursuits.jpg
    - lib/assets/weekend_plans/culinary_delights.jpg
    - lib/assets/commuting/eco_friendly_commuting.jpg
    - lib/assets/commuting/alternative_commuting_methods.jpg
    - lib/assets/commuting/smart_commuting_tips.jpg
    - lib/assets/pet_ownership/choosing_the_right_pet.jpg
    - lib/assets/pet_ownership/preparing_your_home_for_a_pet.jpg
    - lib/assets/pet_ownership/training_and_socializing_your_pet.jpg
    - lib/assets/music/exploring_different_music_genres.jpg
    - lib/assets/music/music_production_basics.jpg
    - lib/assets/music/music_theory_fundamentals.jpg
    - lib/assets/travel/adventure_travel_destinations.jpg
    - lib/assets/travel/adventure_destinations.jpg
    - lib/assets/work_life_balance/healthy_work-life_balance.jpg
    - lib/assets/work_life_balance/managing_stress_and_burnout.jpg
    - lib/assets/work_life_balance/building_supportive_relationships.jpg
    - lib/assets/learning_languages/effective_language_learning_strategies.jpg
    - lib/assets/learning_languages/exploring_language_learning_apps.png
    - lib/assets/learning_languages/tips_for_effective_language_learning.jpg
    - lib/assets/family_time/board_games2.jpg
    - lib/assets/parent_tips/effective_parenting_strategies.jpg
    - lib/assets/parent_tips/effective_communication_with_teenagers.jpg
    - lib/assets/parent_tips/promoting_healthy_eating_habits.jpg
    - lib/assets/home_decor/creating_a_cozy_living_room.jpg
    - lib/assets/home_decor/organizing_small_spaces.jpg
    - lib/assets/home_decor/creating_a_relaxing_bedroom_retreat.jpg
    - lib/assets/book_recommendations/classic_novels_for_every_bookworm.jpg
    - lib/assets/book_recommendations/contemporary_fiction_must_reads.jpg
    - lib/assets/book_recommendations/sci-Fi_classics.jpg
    - lib/assets/financial_planning/building_an_emergency_fund.jpg
    - lib/assets/financial_planning/retirement_savings_strategies.jpg
    - lib/assets/financial_planning/debt_management_strategies.jpg
    - lib/assets/friendships/building_strong_and_meaningful_friendships.jpg
    - lib/assets/friendships/nurturing_long-distance_friendships.jpg
    - lib/assets/friendships/maintaining_healthy_boundaries_in_friendships.jpg
    - lib/assets/fashion_trends/current_fashion_trends_2023_edition.jpg
    - lib/assets/fashion_trends/edgy_streetwear_style.jpg
    - lib/assets/fashion_trends/sustainable_fashion_eco-Conscious_style.jpg
    - lib/assets/mental_health/self-Care_practices_for_mental_well-being.jpg
    - lib/assets/mental_health/coping_with_stress_and_anxiety.jpg
    - lib/assets/mental_health/building_healthy_relationships.jpg
    - lib/assets/productivity/time_management_strategies.jpg
    - lib/assets/productivity/effective_task_management.jpg
    - lib/assets/productivity/creating_a_productive_work_environment.jpg
    - lib/assets/gaming/choosing_the_right_gaming_platform.jpg
    - lib/assets/gaming/improving_gameplay_skills.jpg
    - lib/assets/gaming/building_a_gaming_community.jpg
    - lib/assets/art_and_crafts/introduction_to_drawing.jpg
    - lib/assets/art_and_crafts/exploring_watercolor_painting.jpg
    - lib/assets/art_and_crafts/introduction_to_pottery.jpg
    - lib/assets/healthy_eating/plant-Based_nutrition.jpg
    - lib/assets/healthy_eating/mindful_eating_for_a_healthy_relationship_with_food.jpg
    - lib/assets/healthy_eating/meal_prep_and_healthy_eating.jpg
    - lib/assets/job_search/creating_an_effective_resume.jpg
    - lib/assets/job_search/preparing_for_a_job_interview.jpg
    - lib/assets/job_search/networking_for_job_opportunities.jpg
    - lib/assets/relationship_advice/effective_communication_in_relationships.jpg
    - lib/assets/relationship_advice/maintaining_healthy_boundaries_in_relationships.jpg
    - lib/assets/relationship_advice/building_trust_in_relationship.jpg
    - lib/assets/sustainable_living/reducing_waste_and_recycling.jpg
    - lib/assets/art_crafts_b_.gif
    - lib/assets/book_recommendations_b.gif
    - lib/assets/commuting_b.gif
    - lib/assets/pet_ownership_b.gif
    - lib/assets/music_b.gif
    - lib/assets/travel_b.gif
    - lib/assets/work_life_balance_b.gif
    - lib/assets/learning_languages_b.gif
    - lib/assets/parenting_tips_b.gif
    - lib/assets/home_decor_b.gif
    - lib/assets/book_recommendations_b.gif
    - lib/assets/financial_planning_b.gif
    - lib/assets/friendships_b.gif
    - lib/assets/fashion_trends_b.gif
    - lib/assets/mental_health_b.gif
    - lib/assets/productivity_tips_b.gif
    - lib/assets/gaming_b.gif
    - lib/assets/art_crafts_b_.gif
    - lib/assets/healthy_eating_b.gif
    - lib/assets/job_search_tips_b.gif
    - lib/assets/relationship_advice_b.gif
    - lib/assets/sustainable_living_b.gif
    - lib/assets/self_improvement_b.gif
    - lib/assets/wellness_tips_b.gif
    - lib/assets/entrepreneurship_b.gif
    - lib/assets/gardening_tips_b.gif
    - lib/assets/positive_affirmations_b.gif
    - lib/assets/online_learning_b.gif
    - lib/assets/fundraising_ideas_b.gif
    - lib/assets/sports_b.gif
    - lib/assets/restaurante_b.gif
    - lib/assets/supermarket_b.gif
    - lib/assets/public_transport_b.gif
    - lib/assets/bank_b.gif
    - lib/assets/hospital_b.gif
    - lib/assets/morning_routine_b.gif
    - lib/assets/cooking_recipes_b.gif
    - lib/assets/fitness_exercise_b.gif
    - lib/assets/family_b.gif
    - lib/assets/technology_gadgets_b.gif
    - lib/assets/weekend_plans_b.gif
    - lib/data/vertical_items.json
    - lib/data/favorite_items.json
    - lib/data/all_items.json
    - lib/data/topics.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
